Web server
jedyEvgeny/YPGoFinalJob pull request #1
Opened 2024-04-25 11:17 UTC by jedyEvgeny

2024-04-25 20:24 UTC, robotomize requested changes
Привет, хорошая работа, но есть несколько вещей которые нужно поправить. Это обработка ошибок в базе данных и при запуске сервера, некоторые статусы и нейминг. Остальные вещи тоже лучше поправить, но те что можете или считаете уместным

2024-04-25 20:24 UTC, robotomize commented on database/database.go
> +func createSchedulerTable(db *sql.DB) {
Тут лучше вернуть ошибку, чтобы мы могли обработать ситуацию когда база не создалась

2024-04-25 20:24 UTC, robotomize commented on database/database.go
> +func InitDatabase() {
Тут лучше вернуть ошибку, чтобы мы могли обработать ситуацию когда база не создалась

2024-04-25 20:24 UTC, robotomize commented on tasks/taskHandler.go
> +package task
Именование файлов, task_handler.go, task_maker.go

2024-04-25 20:24 UTC, robotomize commented on datecalculator/datecalculate.go
> +package datecalculator
Именование файлов, date_calculate.go

2024-04-25 20:24 UTC, robotomize commented on database/taskDatabaseHandler.go
> +package database
Именование файлов, task_database_handler.go

2024-04-25 20:24 UTC, robotomize commented on database/taskDatabaseHandler.go
> +package database
Но лучше назвать это repository.go так будет идея в том, что мы вынесли слой работы с БД в понятную историю

2024-04-25 20:24 UTC, robotomize commented on database/taskDatabaseHandler.go
> +package database
Я бы вообще вынес все кроме main в internal папку, где были бы отдельные пакеты database, calculate и прчоее, это необязательный фикс

2024-04-25 20:24 UTC, robotomize commented on main.go
> +	database.InitDatabase()
Вот тут если БД не создалась или что-то с подключеним мы об этом не узнаем и запускаем наш сервер

2024-04-25 20:24 UTC, robotomize commented on main.go
> +	fmt.Fprintln(w, nextDate)
Я бы обработал тут ошибку, что если соединение было разорвано, мы хотя бы залогируем эту ошибку через fmt, slog, log пакеты на выбор

2024-04-25 20:24 UTC, robotomize commented on tasks/taskMaker.go
> +		fmt.Fprintln(w, `{"error":"не указан заголовок задачи"}`)
Я бы обрабатывал подобные ошибки и логировал бы их

2024-04-25 20:24 UTC, robotomize commented on main.go
> +	http.ListenAndServe(port, nil)
Если сервер не стартанул мы даже не узнаем почему это произошло, нужно обработать ошибку

2024-04-25 20:24 UTC, robotomize commented on database/database.go
> +	  CREATE INDEX idx_date ON scheduler (date);
Тут всегда будет ошиька, потому что первая и вторая операция независимы. Нужно сделать create index if not exist

2024-04-25 20:24 UTC, robotomize commented on database/taskDatabaseHandler.go
> +
rows.Err() нужно еще проверить

2024-04-25 20:24 UTC, robotomize commented on tasks/taskMaker.go
> +	if err != nil {
Что если тут будет ошибка доступа к БД? Нужно првоерить конкретную ошибку как то так if errros.Is(err, sql.ErrNoRows) дополнительно к проверке if err != nil если ошибка именно отсутствия значений выдать NotFound, в остальных случаях отдать InternalServerError так как какая-то неизвестная история произошла и залогировать ошибку

2024-04-25 20:24 UTC, robotomize commented on tasks/taskMaker.go
> +		w.Write([]byte(`{"error": "Задача не найдена"}`))
Мы тут отдаем JSON а content-type заголовок устанавливаем ниже по коду. Так как в ошибках мы также отдаем JSON нужно инициализировать заголовки в самом начале. Это относится ко всем хэндлерам, где может быть подобное поведение

2024-04-25 20:24 UTC, robotomize commented on database/taskDatabaseHandler.go
> +func TaskExists(taskID string) bool {
У нас уже есть метод получения задачи по ID. В целом использовать count для этой задачи не особого смысла не имеет, можно переиспользовать метод получения задачи

2024-04-25 20:24 UTC, robotomize commented on tasks/taskMaker.go
> +	if !database.TaskExists(task.ID) {
Тут в целом может и нет смысла делать эту проверку. МОжем в конце пробовать обновить и если количество строк для обновления нам вышло 0, то задачи нет. Я не считаю это ошибкой, просто на будущее

2024-04-25 20:24 UTC, robotomize commented on tasks/taskMaker.go
> +		w.WriteHeader(http.StatusNotFound)
Более правильно тут отдать BadRequest так как пустой идентификатор это не валидное значение

2024-04-25 20:24 UTC, robotomize commented on tasks/taskMaker.go
> +		w.WriteHeader(http.StatusNotFound)
Не знаю как по условию задачи, поэтому не буду считать это ошибкой, но удаление чаще всего идемпотентная операция, которую мы можем безопасно повторить с ожидаемым результатом. То есть если задачи нет, ну и хорошо=) Если есть удалили ее.

2024-04-25 20:24 UTC, robotomize commented on tasks/taskMaker.go
> +		w.WriteHeader(http.StatusNotFound)
Но статус тут не правильный. Мы можем внутри базы данных теретически првоерить, что количество затронутых строк 0 и поэтому типа задачи нет, хотя я выше написал почему это не лучшая стратегия. В вашем коде проекта тут в любом случае надо отдать скорее InternalServerError статус, так как там может быть только ошибка с БД

2024-05-01 03:13 UTC, jedyEvgeny commented on database/database.go
> +func createSchedulerTable(db *sql.DB) {
Поправил

2024-05-01 03:13 UTC, jedyEvgeny commented on database/database.go
> +func InitDatabase() {
Поправил

2024-05-01 03:14 UTC, jedyEvgeny commented on tasks/taskHandler.go
> +package task
Сделано. Эта тема кстати в уроках не освещалась, я почему-то думал что раз в синтаксисе го принят КэмелКейс, то и в именовании файлов такой же стиль. А вон как

2024-05-01 03:14 UTC, jedyEvgeny commented on datecalculator/datecalculate.go
> +package datecalculator
Готово

2024-05-01 03:14 UTC, jedyEvgeny commented on database/taskDatabaseHandler.go
> +package database
Принято

2024-05-01 03:14 UTC, jedyEvgeny commented on database/taskDatabaseHandler.go
> +func TaskExists(taskID string) bool {
Да, действительно

2024-05-01 03:17 UTC, jedyEvgeny commented on tasks/taskMaker.go
> +	if !database.TaskExists(task.ID) {
В законченной версии функции действительно смысла нет в этой проверке, т.к. этот фрагмент кода по смыслу дублирует следующая более расширенная проверка - на наличие ID в БД. Соответственно, если из запроса условного ID == "Бурайди" не будет в БД, то всё равно возникнет ожидаемая ошибка. Но когда писал эту проверку, следующей функции ещё написано не было. Сейчас удалил просто

2024-05-01 03:17 UTC, jedyEvgeny commented on tasks/taskMaker.go
> +		w.WriteHeader(http.StatusNotFound)
Пока статусы ответа - слабое место. Просто принимаю как данность

2024-05-01 03:18 UTC, jedyEvgeny commented on tasks/taskMaker.go
> +		w.WriteHeader(http.StatusNotFound)
Вот ТЗ: Удаление задачи
Бывают ситуации, когда задача потеряла актуальность и её нужно просто удалить. На фронтенде в браузере для этого есть иконка в виде корзины. Добавьте в хендлер /api/task обработку запроса с методом DELETE - /api/task/done?id=<идентификатор>. В этом случае нужно удалить из таблицы scheduler задачу с указанным идентификатором.
Ответ сервера должен быть аналогичен ответу на запрос /api/task/done. Нужно возвращать {} или, **в случае ошибки, JSON с полем error.**
Проверьте функцию удаления задач, как обычно, с помощью тестов go test -run ^TestDelTask$ ./tests, а затем в браузере.

Соответственно, полезно сообщить разработчикам курса об идемпотентности операции)

2024-05-01 03:19 UTC, jedyEvgeny commented on tasks/taskMaker.go
> +		w.WriteHeader(http.StatusNotFound)
Про статусы написал выше, пока принимаю как данность и со временем начну лучше в них разбираться. Когда практики больше будет

2024-05-01 13:41 UTC, robotomize commented on tasks/taskHandler.go
> +package task
Я думаю так у многих да

2024-05-01 13:43 UTC, robotomize commented on tasks/taskMaker.go
> +		w.WriteHeader(http.StatusNotFound)
Хорошо, по смыслу тут лучше понять что вернет метод, если ошибка что не удалилось потому что ничего нет, то тут как писал выше, если ошибка с БД InternalServerError

2024-05-01 13:44 UTC, robotomize approved these changes
Отлично, принято, рад, что ответили на комменты, стало немного более понятно относительно моих комментов, мне же=)

2024-05-09 12:14 UTC, merged